version: '2'
services:
    api_test_demo-app:
        image: api_test_demo
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://api_test_demo-mysql:3306/api_test_demo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    api_test_demo-mysql:
        extends:
            file: mysql.yml
            service: api_test_demo-mysql
